spring:
  main:
    headless: false    # WICHTIG f√ºr Swing UI

server:
  port: 9000           # REST-Callback dieses Clients

alcatraz:
  self:
    name: "Alice"
    callbackBaseUrl: "http://localhost:9000"
  registry:
    nodes:
      - "http://localhost:8080"
      - "http://localhost:8081"
      - "http://localhost:8082"
